sonar.projectKey=juandata-dev_pipedream
sonar.organization=juandata-dev
sonar.coverage.exclusions=/tests/,/src/vista/,/docs/,/setup.ts*,/.spec.ts*,/node_modules/*
sonar.javascript.lcov.reportPaths=coverage/lcov.info 
